package service

import (
	"errors"
	"strings"
)

// unsafePathCharacters cannot appear in any path that reaches a generated unit
// file or scheduled-task definition.
//
// NUL, CR and LF are the darwin validate() set. A systemd unit file is
// line-oriented "Key=Value", so a newline inside ExecStart does not corrupt the
// file, it appends a directive of the attacker's choosing - and neither CR nor
// LF has an escape in that format, so there is nothing to escape them into.
// The quote characters are rejected on top of that: systemd's command line is
// word-split with shell-like quoting, and the Windows Arguments string is
// re-split by CommandLineToArgvW, so an unbalanced quote in a path silently
// changes which arguments the service is started with. Both renderers still
// escape what they emit; this is the outer fence, not the only one.
const unsafePathCharacters = "\x00\r\n\"'"

// checkRenderablePaths rejects values that cannot be safely placed in a
// generated service definition. It deliberately does not check absoluteness:
// that is filepath.IsAbs, which is platform-dependent, and belongs to each
// Manager's validate() where it runs against its own platform's rules.
func checkRenderablePaths(values ...string) error {
	for _, value := range values {
		if value == "" {
			return errors.New("service executable, config root, and home must be explicit")
		}
		if strings.ContainsAny(value, unsafePathCharacters) {
			return errors.New("service paths contain invalid characters")
		}
	}
	return nil
}

// unitSpec is everything the systemd user unit is rendered from.
type unitSpec struct {
	Label      string
	Executable string
	ConfigRoot string
}

// serviceArguments is the argument vector the job is started with. It is the
// same list the LaunchAgent's ProgramArguments carries, so the three platforms
// cannot start the service with different flags.
func serviceArguments(executable, configRoot string) []string {
	return []string{executable, "--config-root", configRoot, "service", "run"}
}

// renderUnit produces the systemd user unit for a profile.
//
// Restart=always with RestartSec=5 is the LaunchAgent's KeepAlive plus
// ThrottleInterval=5, and WantedBy=default.target is RunAtLoad for a user
// session: the user manager pulls default.target in at login.
func renderUnit(spec unitSpec) (string, error) {
	if err := checkRenderablePaths(spec.Executable, spec.ConfigRoot); err != nil {
		return "", err
	}
	if spec.Label == "" || strings.ContainsAny(spec.Label, unsafePathCharacters+" \t/") {
		return "", errors.New("service label is not a usable systemd unit name")
	}
	quoted := make([]string, 0, 5)
	for _, argument := range serviceArguments(spec.Executable, spec.ConfigRoot) {
		quoted = append(quoted, systemdQuote(argument))
	}
	var b strings.Builder
	b.WriteString("# Generated by \"overgent service install\". Edits are replaced on the next\n")
	b.WriteString("# install; change the profile instead.\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=Overgent coordination service\n")
	// launchd's KeepAlive restarts the job forever, throttled by
	// ThrottleInterval. systemd would instead give up permanently once
	// StartLimitBurst restarts land inside StartLimitIntervalSec, which turns a
	// transient crash loop into a service that is simply gone until someone
	// notices. Disabling the start limit and leaving RestartSec to do the
	// throttling is what actually matches KeepAlive.
	b.WriteString("StartLimitIntervalSec=0\n")
	b.WriteString("\n[Service]\n")
	b.WriteString("Type=simple\n")
	b.WriteString("ExecStart=" + strings.Join(quoted, " ") + "\n")
	b.WriteString("Restart=always\n")
	b.WriteString("RestartSec=5\n")
	// The service holds a Unix socket and a lock file; give it a moment to
	// release them rather than having systemd SIGKILL the group immediately.
	b.WriteString("KillMode=mixed\n")
	b.WriteString("TimeoutStopSec=15\n")
	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")
	return b.String(), nil
}

// systemdQuote renders one ExecStart word as a systemd double-quoted string.
//
// systemd expands "%" specifiers (%h, %u, ...) in unit values before it splits
// the command line, so a literal percent has to be doubled or a path containing
// one is rewritten into something else entirely. Inside double quotes systemd
// then applies C-style unescaping, so backslash and the quote character have to
// be escaped as well. Quoting unconditionally means a path containing spaces -
// "Application Support" on the macOS-shaped profiles, "Program Files" on a
// shared checkout - stays one argument.
func systemdQuote(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "%", "%%")
	return `"` + escaped + `"`
}

// unitNotFound reports that systemctl refused because there is no such unit,
// which for Stop and Remove means the desired end state already holds. It is
// the systemd counterpart of the darwin notLoaded.
func unitNotFound(err error) bool {
	return mentions(err,
		"not loaded",
		"not found",
		"does not exist",
		"no such file or directory",
		"no such unit",
	)
}

// alreadyRunning reports that systemctl refused a start because the unit is
// already active, which is also the desired end state. It is the systemd
// counterpart of the darwin alreadyLoaded.
func alreadyRunning(err error) bool {
	return mentions(err,
		"already active",
		"already running",
		"already started",
	)
}

// noUserBus reports that systemctl could not reach a systemd user manager at
// all. This is not a fault in the unit: it means there is no per-user systemd
// instance to own it, which is exactly the WSL2-without-systemd and
// no-session case, so callers turn it into the actionable environment error
// rather than surfacing "Failed to connect to bus" to a member.
func noUserBus(err error) bool {
	return mentions(err,
		"failed to connect to bus",
		"no medium found",
		"dbus_session_bus_address",
		"xdg_runtime_dir",
		"connection refused",
		"system has not been booted with systemd",
	)
}
